name: boundedv2

num_target_views: 4
num_context_views: 4

min_distance_between_context_views: 20
max_distance_between_context_views: 40
max_distance_to_context_views: 0

context_gap_warm_up_steps: 0
target_gap_warm_up_steps: 0

initial_min_distance_between_context_views: 10
initial_max_distance_between_context_views: 20
initial_max_distance_to_context_views: 0
extra_views_sampling_strategy: farthest_point
target_views_replace_sample: false
