defaults:
  - view_sampler: boundedv2_360

name: dl3dv
roots: [datasets/dl3dv]
make_baseline_1: false
augment: true

image_shape: [224, 448]
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false

baseline_epsilon: 1e-3
max_fov: 100.0

skip_bad_shape: true
near: -1.
far: -1.
baseline_scale_bounds: false
shuffle_val: true
test_len: -1
test_chunk_interval: 1
sort_target_index: true
sort_context_index: true

train_times_per_scene: 1
test_times_per_scene: 1
ori_image_shape: [270, 480]
overfit_max_views: 148
use_index_to_load_chunk: true
skip_error_data: false

mix_tartanair: false
no_mix_test_set: true
load_depth: false
