# @package _global_

dataset:
  view_sampler:
    min_distance_between_context_views: 10
    max_distance_between_context_views: 40 # 90
    max_distance_to_context_views: 0 # 90
    context_gap_warm_up_steps: 0   # 150_000
    target_gap_warm_up_steps: 0  # 50_000
    initial_min_distance_between_context_views: 10
    initial_max_distance_between_context_views: 20 # 45
    initial_max_distance_to_context_views: 0  # 0
    extra_views_sampling_strategy: farthest_point
    num_target_views: 4
