# @package _global_

dataset:
  view_sampler:
    index_path: assets/evaluation_index_re10k.json

evaluation:
  methods:
    - name: Ours
      key: ours
      path: outputs/test/re10k
    - name: Ours (3 Views)
      key: ours_3_view
      path: outputs/test/re10k_3_view

  side_by_side_path: null
  animate_side_by_side: false
  highlighted:
    # Main Paper
    - scene: 5be4f1f46b408d68
      target_index: 136
    - scene: 800ea72b6988f63e
      target_index: 167
    - scene: d3a01038c5f21473
      target_index: 201
    

output_metrics_path: baselines/re10k/evaluation_metrics_3_view.json