name: depthsplat

opacity_mapping:
  initial: 0.0
  final: 0.0
  warm_up: 1
  no_mapping: false

num_depth_candidates: 128
num_surfaces: 1

gaussians_per_pixel: 1

gaussian_adapter:
  gaussian_scale_min: 0.1
  gaussian_scale_max: 0.3
  sh_degree: 4

d_feature: 128

visualizer:
  num_samples: 8
  min_resolution: 256
  export_ply: false

unimatch_weights_path: "pretrained/gmdepth-scale1-resumeflowthings-scannet-5d9d7964.pth"
multiview_trans_attn_split: 2
costvolume_unet_feat_dim: 128
costvolume_unet_channel_mult: [1,1,1]
costvolume_unet_attn_res: []
depth_unet_feat_dim: 64
depth_unet_attn_res: []
depth_unet_channel_mult: [1, 1, 1]
downscale_factor: 4
shim_patch_size: 4

costvolume_nearest_n_views: null
multiview_trans_nearest_n_views: null

# monodepth
monodepth_vit_type: vits

# return depth
supervise_intermediate_depth: true
return_depth: false

# mv_unimatch
upsample_factor: 4
lowest_feature_resolution: 4
depth_unet_channels: 128
grid_sample_disable_cudnn: true
no_cross_attn: False
use_cost_volume: True
use_cluster: True
cluster_num: 2
min_cluster_num: 0
max_cluster_num: 0
num_zpressor_layers: 6
cluster_group: []
apply_cluster_steps: 0
use_clstoken: False
use_avg_token: False
no_self_attn: False

# depthsplat color branch
large_gaussian_head: false
color_large_unet: false
init_sh_input_img: true
feature_upsampler_channels: 64
gaussian_regressor_channels: 64

# only depth
train_depth_only: false
